# Generated by Django 5.2.8 on 2025-12-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member', max_length=200)),
                ('title', models.CharField(help_text='Job title/position (e.g., CEO & Founder • System Engineer)', max_length=300)),
                ('bio', models.TextField(help_text='Biography/description of the team member')),
                ('image', models.ImageField(help_text='Profile photo of team member', upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500, null=True)),
                ('portfolio_url', models.URLField(blank=True, help_text='Portfolio website URL', max_length=500, null=True)),
                ('website_url', models.URLField(blank=True, help_text='Personal website URL', max_length=500, null=True)),
                ('cv_url', models.URLField(blank=True, help_text='CV/Resume URL', max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this team member')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
