# Generated by Django 5.2.8 on 2025-12-15 09:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(help_text='Profile photo of team member', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='team/'),
        ),
    ]
