# Generated by Django 5.2.8 on 2026-03-22 21:24

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_teammember_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_svg', models.TextField(blank=True, help_text='Raw SVG path or heroicon name')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consultancy Service',
                'verbose_name_plural': 'Consultancy Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConsultingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('client', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projects/')),
                ('link', models.URLField(blank=True, help_text='Link to the project or case study')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consulting Project',
                'verbose_name_plural': 'Consulting Projects',
                'ordering': ['-completed_at', 'order'],
            },
        ),
    ]
