# Generated by Django 5.1.7 on 2025-09-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 3 months, 6 weeks', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='features',
            field=models.TextField(blank=True, help_text='Enter features separated by new lines', null=True),
        ),
    ]
